//! AST for ESLD (spec §6 grammar).
//!
//! The AST mirrors the grammar closely enough for the IR to walk it and
//! for the formatter to be a token-stream renderer (§ `fmt`), so unknown
//! properties, comments, and ordering survive round-trip by construction.

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Span {
    /// 1-based line of the construct's first token.
    pub line: u32,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    /// Number with optional unit (`63A`), kept as source text.
    Quantity {
        number: String,
        unit: String,
    },
    /// Bare number.
    Number(String),
    Bool(bool),
    Str(String),
    /// Identifier, enum value, or dotted reference joined with `.`.
    Ident(String),
    List(Vec<ValueNode>),
    Range(Box<ValueNode>, Box<ValueNode>),
    Block(Vec<Property>),
}

impl Value {
    /// Numeric value with the unit normalized to a base multiplier for
    /// known unit families (V/A/W/Hz); `None` for non-numeric values.
    pub fn quantity(&self) -> Option<(f64, String)> {
        let (number, unit) = match self {
            Value::Quantity { number, unit } => (number.clone(), unit.clone()),
            Value::Number(number) => (number.clone(), String::new()),
            _ => return None,
        };
        let n: f64 = number.parse().ok()?;
        let (mult, base) = normalize_unit(&unit);
        Some((n * mult, base))
    }

    /// Reference parts if this value is a (possibly dotted) identifier.
    pub fn as_ref(&self) -> Option<Vec<String>> {
        match self {
            Value::Ident(s) => Some(s.split('.').map(str::to_owned).collect()),
            _ => None,
        }
    }

    pub fn as_str(&self) -> Option<&str> {
        match self {
            Value::Str(s) => Some(s),
            _ => None,
        }
    }

    pub fn as_ident(&self) -> Option<&str> {
        match self {
            Value::Ident(s) => Some(s),
            _ => None,
        }
    }
}

/// Metric prefixes recognized on units; `kW` -> 1e3, `mV` -> 1e-3, …
fn normalize_unit(unit: &str) -> (f64, String) {
    const BASES: &[&str] = &["V", "A", "W", "VA", "var", "Wh", "Hz", "ohm", "m", "s", ""];
    // A complete base unit is never prefix-stripped — most importantly
    // bare "m" (metres) must not become milli-nothing.
    if BASES.contains(&unit) {
        return (1.0, unit.to_string());
    }
    let Some(first) = unit.chars().next() else {
        return (1.0, String::new());
    };
    // 'µ' is multi-byte in UTF-8 — slice by the first char's length.
    let tail = &unit[first.len_utf8()..];
    let (mult, rest) = match first {
        'k' | 'K' => (1e3, tail),
        'M' => (1e6, tail),
        'm' => (1e-3, tail),
        'u' | 'µ' => (1e-6, tail),
        _ => (1.0, unit),
    };
    // Only treat the prefix as such for known base units.
    if BASES.contains(&rest) {
        (mult, rest.to_string())
    } else {
        (1.0, unit.to_string())
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct ValueNode {
    pub value: Value,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Property {
    pub name: String,
    pub value: ValueNode,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Endpoint {
    /// Dotted reference text as written (`MAIN.MSB.in`).
    pub text: String,
    pub phases: Vec<String>,
    pub span: Span,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Arrow {
    Fwd,
    Rev,
    Peer,
}

impl Arrow {
    pub fn as_str(self) -> &'static str {
        match self {
            Arrow::Fwd => "->",
            Arrow::Rev => "<-",
            Arrow::Peer => "--",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum VoltsysBody {
    Positional(ValueNode, ValueNode, ValueNode),
    Block(Vec<Property>),
}

/// Inline device instantiation (`protection : rcbo { … };` inside a
/// circuit) — the tag is auto-generated by the IR.
#[derive(Debug, Clone, PartialEq)]
pub struct InlineDevice {
    pub type_ref: String,
    pub props: Vec<Property>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CircuitItem {
    Property(Property),
    Protection(InlineDevice),
    Controller(InlineDevice),
    Node(NodeDecl),
    Connect(ConnectStmt),
    Note(NoteStmt),
}

#[derive(Debug, Clone, PartialEq)]
pub struct NodeDecl {
    pub tag: String,
    pub type_ref: String,
    pub props: Vec<Property>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct NoteStmt {
    pub text: String,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ConnectStmt {
    /// Endpoints and arrows alternate: `a -> b -- c` is
    /// endpoints `[a, b, c]`, arrows `[Fwd, Peer]`.
    pub endpoints: Vec<ValueNode>,
    pub arrows: Vec<Arrow>,
    pub attrs: Vec<Property>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum BoardItem {
    Property(Property),
    Node(NodeDecl),
    Bus(BusDecl),
    Circuit(CircuitDecl),
    Connect(ConnectStmt),
    Note(NoteStmt),
}

#[derive(Debug, Clone, PartialEq)]
pub struct BusDecl {
    pub tag: String,
    pub type_ref: Option<String>,
    pub props: Vec<Property>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CircuitDecl {
    pub tag: String,
    pub type_ref: Option<String>,
    pub items: Vec<CircuitItem>,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum StateItem {
    Use(String, Span),
    Position {
        target: ValueNode,
        position: String,
        span: Span,
    },
    Note(NoteStmt),
}

#[derive(Debug, Clone, PartialEq)]
pub struct ScenarioItemRaw {
    /// Kind keyword: `set`, `expect`, `use`.
    pub kind: String,
    /// Remaining tokens' canonical text, joined with single spaces.
    pub text: String,
    pub span: Span,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Statement {
    Profile {
        value: String,
        span: Span,
    },
    Include {
        path: String,
        span: Span,
    },
    Note(NoteStmt),
    Voltsys {
        name: String,
        body: VoltsysBody,
        span: Span,
    },
    Code {
        name: String,
        props: Vec<Property>,
        span: Span,
    },
    /// Type declarations are depth-skipped for now; the name is kept so
    /// the IR can resolve user types (R-101).
    TypeDecl {
        name: String,
        span: Span,
    },
    Node(NodeDecl),
    Board {
        tag: String,
        type_ref: Option<String>,
        items: Vec<BoardItem>,
        span: Span,
    },
    Group {
        name: String,
        list: ValueNode,
        span: Span,
    },
    Connect(ConnectStmt),
    /// Vendor blocks are depth-skipped.
    Vendor {
        span: Span,
    },
    Scenario {
        name: String,
        items: Vec<ScenarioItemRaw>,
        span: Span,
    },
    State {
        name: String,
        items: Vec<StateItem>,
        span: Span,
    },
    Interlock {
        name: String,
        requires: Vec<String>,
        span: Span,
    },
    Zone {
        name: String,
        props: Vec<Property>,
        span: Span,
    },
    Layout {
        items: Vec<LayoutItem>,
        span: Span,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum LayoutItem {
    Property(Property),
    Target {
        target: String,
        props: Vec<Property>,
        span: Span,
    },
    Note(NoteStmt),
}

#[derive(Debug, Clone, PartialEq)]
pub struct Document {
    pub statements: Vec<Statement>,
}
